# Generated by Django 2.2.10 on 2020-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(max_length=200, verbose_name='Дата монтажа'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img1',
            field=models.ImageField(upload_to='static/img/project_img', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img2',
            field=models.ImageField(upload_to='static/img/project_img', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img3',
            field=models.ImageField(upload_to='static/img/project_img', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img4',
            field=models.ImageField(upload_to='static/img/project_img', verbose_name='Изображение 4'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img5',
            field=models.ImageField(upload_to='static/img/project_img', verbose_name='Изображение 5'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img6',
            field=models.ImageField(upload_to='static/img/project_img', verbose_name='Изображение 6'),
        ),
        migrations.AlterField(
            model_name='project',
            name='jobs',
            field=models.CharField(max_length=200, verbose_name='Выполненые работы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='object',
            field=models.CharField(max_length=200, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.CharField(max_length=200, verbose_name='Общая стоимость проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='task',
            field=models.CharField(max_length=200, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumb1',
            field=models.ImageField(upload_to='static/img/project_img/', verbose_name='Миниатюра 1 (334x500)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumb2',
            field=models.ImageField(upload_to='static/img/project_img/', verbose_name='Миниатюра 2 (334x500)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumb3',
            field=models.ImageField(upload_to='static/img/project_img/', verbose_name='Миниатюра 3 (334x500)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumb4',
            field=models.ImageField(upload_to='static/img/project_img/', verbose_name='Миниатюра 4 (1000x500)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumb5',
            field=models.ImageField(upload_to='static/img/project_img/', verbose_name='Миниатюра 5 (500x1000)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumb6',
            field=models.ImageField(upload_to='static/img/project_img/', verbose_name='Миниатюра 6 (500x1000)'),
        ),
    ]
